---
version: "3.8"

services:
  php:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: php-fpm
    volumes:
      - "./apps/back:/usr/src/app"
    restart: unless-stopped
    command: ["php-fpm"]
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: dev
      APP_SECRET: changeme
      APP_URL: "http://localhost"
      DATABASE_URL: "mysql://user:password@db:3306/database?serverVersion=8.0.32&charset=utf8mb4"

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./apps/back/public:/usr/src/app/public
    restart: unless-stopped
  db:
    image: mysql:8.0.32
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [CMD, mysqladmin, ping, --silent]
    ports:
      - 3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  mailhog:
    image: mailhog/mailhog
    restart: on-failure
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  db:
