---
version: '3.8'

services:
    php:
        platform: linux/x86_64
        image: knplabs/qpqalexandre:php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            target: php-fpm
        restart: unless-stopped
        command: [ "php-fpm" ]
        depends_on:
            db:
                condition: service_healthy
        environment:
            APP_ENV: prod
            APP_SECRET: changeme
            APP_URL: "http://localhost"
            DATABASE_URL: "mysql://user:password@db:3306/database?serverVersion=8.0.32&charset=utf8mb4"
    nginx:
        image: knplabs/qpqalexandre:nginx
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            target: nginx
        ports:
            - 80:80
        restart: unless-stopped
        depends_on:
            - php
    db:
        image: mysql:8.0.32
        restart: unless-stopped
        volumes:
            - db:/var/lib/mysql
        healthcheck:
            test: [ CMD, mysqladmin, ping, --silent ]
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=database
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
volumes:
    db:
