parameters:
  APP_URL: "%env(APP_URL)%"

services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
  App\Middleware\ExpenseFailedMiddleWare:
    arguments:
      $maxRetries: "%env(MAX_RETRIES)%"
